Test: Add Flake8 and add to Test script; fix related error in activate
Only ignored directories are venv and __pycache__. Check that there are
no others which should be ignored.

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -7,5 +7,10 @@ cd "$base"
 . ./activate -q
 
 pytest -q "$@"
+echo -e "\r"
 
-echo OK
+flake=$(flake8 --exit-zero --exclude=__pycache__,venv)
+[[ -z $flake ]] && echo -e 'Style checks pass\n' \
+  || { echo -e "Style check errors:\n$flake"; exit 1; }
+
+echo All tests pass
